version: '2'
services:
  spider:
    build: .
    command: python main.py
    volumes:
     - .:/code
    links:
     - redis
     - mongo
    depends_on:
     - redis
     - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
  redis:
    image: redis
    ports:
    - "6379:6379"
